#!/bin/bash

source resources/setup.sh "$@"
set -- $concatenated

exec &> >(tee ${section_01d_logfile})
print_version

# Step 1: decided whether to use a sparse genetic relationship matrix (GRM) and lmm; PCs has been generated by 01b.
# For related data, use all samples, correcting for the full (sparse) GRM.
# Default to no sparse GRM and fastGWA-lr; variables will update based on related/structured flags
use_sparse_grm="no"
fastgwa_mode="lr"
grm_sparse_prefix=""

if [ "${related}" = "yes" ] && [ "${structured}" = "yes" ]; then
    echo "Related + Structured: using PC-Relate sparse GRM from 01b"
    fastgwa_mode="mlm"
    use_sparse_grm="yes"

    if [ -f "${grmfile_pcrelate}.grm.sp" ] && [ -f "${grmfile_pcrelate}.grm.id" ]; then
        grm_sparse_prefix="${grmfile_pcrelate}"
        echo "Using PC-Relate GCTA sparse GRM prefix: ${grm_sparse_prefix}"
    else
        echo "Error: Required PC-Relate sparse GRM files not found:"
        echo "  ${grmfile_pcrelate}.grm.sp"
        echo "  ${grmfile_pcrelate}.grm.id"
        exit 1
    fi

elif [ "${related}" = "yes" ] && [ "${structured}" = "no" ]; then
    echo "Related + non-structured: using KING sparse GRM from 01b"
    fastgwa_mode="mlm"
    use_sparse_grm="yes"
    grm_sparse_prefix="${grmfile_king}_sparse"

    if [ -f "${grmfile_king}_sparse.grm.sp" ] && [ -f "${grmfile_king}_sparse.grm.id" ]; then
        echo "Using KING sparse GRM prefix: ${grm_sparse_prefix}"
    else
        echo "Error: Required KING sparse GRM files not found:"
        echo "  ${grmfile_king}_sparse.grm.sp"
        echo "  ${grmfile_king}_sparse.grm.id"
        exit 1
    fi

elif [ "${related}" = "no" ]; then
    echo "Unrelated sample: no GRM needed (fastGWA-lr)"
    fastgwa_mode="lr"
    use_sparse_grm="no"
    grm_sparse_prefix=""

else
    echo "Error: Invalid related/structured flag combination. Set both to yes or no."
    exit 1
fi

fastgwa_option=()
grm_sparse_option=()
if [ "${use_sparse_grm}" = "yes" ]; then
    fastgwa_option=("--fastGWA-mlm")
    grm_sparse_option=("--grm-sparse" "${grm_sparse_prefix}")
elif [ "${fastgwa_mode}" = "lr" ]; then
    fastgwa_option=("--fastGWA-lr")
else
    echo "Error: Unsupported fastGWA mode: ${fastgwa_mode}"
    exit 1
fi

# Step2: make covar files for gcta input
echo "Splitting covariate files for GCTA"
${R_directory}Rscript resources/methylation/split_covar.R \
    "${covariates_combined}.txt" \
    "${bfile}.fam" \
    "${ccovar_file}" \
    "${qcovar_file}" \
    "${scripts_directory}" \
    "${genetic_pc_gwas}" \
    "${qcovar_noPC_file}"

# Step 3: Checking positive control file
echo "Checking positive control file for 01d"
${R_directory}Rscript resources/genetics/check_positive_controls.R \
    "${positive_control_1d_file}" \
    "${filt_positive_control_1d_file}" \
    "${com_id}" \
    "${methylation_no_outliers_gwas}"

# Step 4: Loop through each positive control locus
echo "Running positive controls"

covar_args=()
if [ -f "${ccovar_file}" ]; then
  ncols=$(awk -F'\t' 'NR==1{print NF; exit}' "${ccovar_file}" 2>/dev/null || echo 0)
  if [ "${ncols}" -gt 2 ]; then
        covar_args=("--covar" "${ccovar_file}")
  else
    echo "No categorical covariates detected in ${ccovar_file}; skipping --covar for GCTA."
  fi
else
  echo "Warning: ccovar file not found: ${ccovar_file}"
fi

############################################################################################################
# positive control
############################################################################################################
base_methylation_no_outliers="${methylation_no_outliers_gwas%.Robj}"

tail -n +2 "${filt_positive_control_1d_file}" | while IFS=$'\t' read -r positive_control_cpg positive_control_snp_chr positive_control_snp_pos rsid positive_control_snp_window positive_control_threshold
do
    echo "Processing positive control: $positive_control_cpg, SNP chr: $positive_control_snp_chr, pos: $positive_control_snp_pos, rsid: $rsid, window: $positive_control_snp_window, threshold: $positive_control_threshold"

    # Get the control CpG
    echo "Extracting methylation values for positive control CpG ${positive_control_cpg}"

    ${R_directory}Rscript -e "load('${methylation_no_outliers_gwas}'); \
                if (!exists('norm.beta')) norm.beta <- get(ls()[1]); \
                row <- norm.beta[rownames(norm.beta) == '${positive_control_cpg}', , drop=FALSE]; \
                ids <- colnames(norm.beta); \
                vals <- as.numeric(row[1,]); \
                df <- data.frame(IID = ids, stringsAsFactors = FALSE); \
                df[['${positive_control_cpg}']] <- vals; \
                write.table(df, file='${base_methylation_no_outliers}.${positive_control_cpg}.positive_control', sep='\t', quote=FALSE, row.names=FALSE, col.names=TRUE)"

    echo "making gcta input for positive control CpG ${positive_control_cpg} (untransformed)"
    nrow=`cat ${base_methylation_no_outliers}.${positive_control_cpg}.positive_control | wc -l`
    if [ "$nrow" -lt "2" ]; then
        echo "The positive control CpG ${positive_control_cpg} appears to be missing for mQTL analysis on untransformed methylation data. Please check."
    else 
        ${R_directory}Rscript resources/genetics/make_control.R \
            "${base_methylation_no_outliers}.${positive_control_cpg}.positive_control" \
            "${intersect_ids_plink}" \
            "${base_methylation_no_outliers}.${positive_control_cpg}.positive_control.gcta"

        echo "Perform fastGWA (untransformed) in positive control"
        if [ "${use_sparse_grm}" = "yes" ]; then
            echo "Using sparse GRM prefix: ${grm_sparse_prefix}"
        else
            echo "No GRM mode: fastGWA-lr"
        fi

        ${gcta} \
            --bfile "${bfile}" \
            "${grm_sparse_option[@]}" \
            "${fastgwa_option[@]}" \
            --h2-limit 100 \
            --pheno "${base_methylation_no_outliers}.${positive_control_cpg}.positive_control.gcta" \
            --qcovar "${qcovar_file}" \
            "${covar_args[@]}" \
            --covar-maxlevel 500 \
            --out "${section_01_dir}/01d/positive_control_untransformed_${positive_control_cpg}" \
            --thread-num "${nthreads}"
        
        tr -s " " < ${section_01_dir}/01d/positive_control_untransformed_${positive_control_cpg}.fastGWA | gzip -c > ${section_01_dir}/01d/positive_control_untransformed_${positive_control_cpg}.fastGWA.gz
        rm ${section_01_dir}/01d/positive_control_untransformed_${positive_control_cpg}.fastGWA

        echo "make manhattan and qq plots (untransformed)"
        echo "${section_01_dir}/01d/positive_control_untransformed_${positive_control_cpg}.fastGWA.gz" > "${section_01_dir}/01d/positive.control.untransformed.file.txt"
        ${R_directory}Rscript resources/genetics/plot_gwas.R \
            "${section_01_dir}/01d/positive.control.untransformed.file.txt" \
            10 \
            8 \
            1 \
            3 \
            2 \
            TRUE \
            "${positive_control_snp_chr}" \
            "${positive_control_snp_pos}" \
            "${positive_control_snp_window}" \
            "${positive_control_threshold}" \
            p
    fi

done

# Step3: Shuffle negative control loci and run the loop again
############################################################################################################
# negative control
############################################################################################################

echo "Running negative control"
# 4 for D, 5 for E, 16 for P
seed=45516

tail -n +2 "${filt_positive_control_1d_file}" | while IFS=$'\t' read -r positive_control_cpg positive_control_snp_chr positive_control_snp_pos rsid positive_control_snp_window positive_control_threshold
do
    negative_control_cpg="NEG_${positive_control_cpg}"

    echo "Processing negative control: $negative_control_cpg"

    echo "Confirming the corresponding positive control exists"
    nrow=`cat ${base_methylation_no_outliers}.${positive_control_cpg}.positive_control | wc -l`
    if [ "$nrow" -lt "2" ]; then
        echo "The positive control CpG ${positive_control_cpg} appears to be missing for mQTL analysis on untransformed methylation data. Please check."
    else
        echo "Shuffle untransformed"
        ${R_directory}Rscript resources/genetics/shuffle_control.R \
            "${base_methylation_no_outliers}.${positive_control_cpg}.positive_control" \
            "${base_methylation_no_outliers}.${negative_control_cpg}.negative_control" \
            "$seed"

        echo "Making gcta input for negative control CpG ${negative_control_cpg} (untransformed)"
        ${R_directory}Rscript resources/genetics/make_control.R \
            "${base_methylation_no_outliers}.${negative_control_cpg}.negative_control" \
            "${intersect_ids_plink}" \
            "${base_methylation_no_outliers}.${negative_control_cpg}.negative_control.gcta"

        echo "Perform GCTA (untransformed) in negative control"
        if [ "${use_sparse_grm}" = "yes" ]; then
            echo "Using sparse GRM prefix: ${grm_sparse_prefix}"
        else
            echo "No GRM mode: fastGWA-lr"
        fi

        ${gcta} \
            --bfile "${bfile}" \
            "${grm_sparse_option[@]}" \
            "${fastgwa_option[@]}" \
            --h2-limit 100 \
            --pheno "${base_methylation_no_outliers}.${negative_control_cpg}.negative_control.gcta" \
            --qcovar "${qcovar_file}" \
            "${covar_args[@]}" \
            --covar-maxlevel 500 \
            --out "${section_01_dir}/01d/negative_control_untransformed_${negative_control_cpg}" \
            --thread-num "${nthreads}"

        tr -s " " < "${section_01_dir}/01d/negative_control_untransformed_${negative_control_cpg}.fastGWA" | gzip -c > "${section_01_dir}/01d/negative_control_untransformed_${negative_control_cpg}.fastGWA.gz"
        rm "${section_01_dir}/01d/negative_control_untransformed_${negative_control_cpg}.fastGWA"

        echo "make manhattan and qq plots (untransformed)"
        echo "${section_01_dir}/01d/negative_control_untransformed_${negative_control_cpg}.fastGWA.gz" > "${section_01_dir}/01d/negative.control.untransformed.file.txt"
        ${R_directory}Rscript resources/genetics/plot_gwas.R \
        "${section_01_dir}/01d/negative.control.untransformed.file.txt" \
            10 \
            8 \
            1 \
            3 \
            2 \
            TRUE \
            "${positive_control_snp_chr}" \
            "${positive_control_snp_pos}" \
            "${positive_control_snp_window}" \
            "${positive_control_threshold}" \
            "p"
    fi

done

echo "Successfully completed script 1d"