#!/bin/bash

source resources/setup.sh "$@"
set -- $concatenated

exec &> >(tee ${section_01d_logfile})
print_version

# Loop through each positive control locus
echo "Running positive controls"

############################################################################################################
# positive control
############################################################################################################

tail -n +2 ./resource/genetics/mqtl_pos_ctr.tsv | while IFS=$'\t' read -r positive_control_cpg positive_control_snp_chr positive_control_snp_pos positive_control_snp_window positive_control_threshold
do
    echo "Processing positive control: $positive_control_cpg"

    # Get the control CPG
    awk -F',' -v cpg=${positive_control_cpg} '{ if(NR == 1 || $1 == cpg) { print $0 }}' ${untransformed_methylation_adjusted_pcs}.csv > ${untransformed_methylation_adjusted}.${positive_control_cpg}.positive_control
    awk -F',' -v cpg=${positive_control_cpg} '{ if(NR == 1 || $1 == cpg) { print $0 }}' ${transformed_methylation_adjusted_pcs}.csv > ${transformed_methylation_adjusted}.${positive_control_cpg}.positive_control

    nrow=`cat ${untransformed_methylation_adjusted}.${positive_control_cpg}.positive_control | wc -l`
    if [ "$nrow" -lt "2" ]; then
        echo "The positive control CPG ${positive_control_cpg} appears to be missing for mQTL analysis on untransformed methylation data. Please check."
        exit
    fi

    ${R_directory}Rscript resources/genetics/make_control.R \
        ${untransformed_methylation_adjusted}.${positive_control_cpg}.positive_control \
        ${intersect_ids_plink} \
        ${untransformed_methylation_adjusted}.${positive_control_cpg}.positive_control.plink

    nrow=`cat ${transformed_methylation_adjusted}.${positive_control_cpg}.positive_control | wc -l`
    if [ "$nrow" -lt "2" ]; then
        echo "The positive control CPG ${positive_control_cpg} appears to be missing for mQTL analysis on transformed methylation data. Please check."
        exit
    fi

    ${R_directory}Rscript resources/genetics/make_control.R \
        ${transformed_methylation_adjusted}.${positive_control_cpg}.positive_control \
        ${intersect_ids_plink} \
        ${transformed_methylation_adjusted}.${positive_control_cpg}.positive_control.plink

    echo "Perform plink (untransformed)"
    ${plink2} \
        --bfile ${bfile} \
        --pheno ${untransformed_methylation_adjusted}.${positive_control_cpg}.positive_control.plink \
        --glm allow-no-covars \
        --allow-extra-chr \
        --human \
        --output-chr 26 \
        --out ${section_03_dir}/positive_control_untransformed_${positive_control_cpg}

    tr -s " " < ${section_03_dir}/positive_control_untransformed_${positive_control_cpg}.PHENO1.glm.linear | gzip -c > ${section_03_dir}/positive_control_untransformed_${positive_control_cpg}.PHENO1.glm.linear.gz
    rm ${section_03_dir}/positive_control_untransformed_${positive_control_cpg}.PHENO1.glm.linear

    echo "make manhattan and qq plots (untransformed)"
    echo ${section_03_dir}/positive_control_untransformed_${positive_control_cpg}.PHENO1.glm.linear.gz > ${section_03_dir}/positive.control.untransformed.file.txt
    ${R_directory}Rscript resources/genetics/plot_gwas.R \
        ${section_03_dir}/positive.control.untransformed.file.txt \
        12 \
        1 \
        2 \
        3 \
        TRUE \
        ${positive_control_snp_chr} \
        ${positive_control_snp_pos} \
        ${positive_control_snp_window} \
        ${positive_control_threshold}

    echo "Perform plink (transformed)"
    ${plink2} \
        --bfile ${bfile} \
        --pheno ${transformed_methylation_adjusted}.${positive_control_cpg}.positive_control.plink \
        --glm allow-no-covars \
        --allow-extra-chr \
        --out ${section_03_dir}/positive_control_transformed_${positive_control_cpg}

    tr -s " " < ${section_03_dir}/positive_control_transformed_${positive_control_cpg}.PHENO1.glm.linear | gzip -c > ${section_03_dir}/positive_control_transformed_${positive_control_cpg}.PHENO1.glm.linear.gz
    rm ${section_03_dir}/positive_control_transformed_${positive_control_cpg}.PHENO1.glm.linear

    echo "make manhattan and qq plots (transformed)"
    echo ${section_03_dir}/positive_control_transformed_${positive_control_cpg}.PHENO1.glm.linear.gz > ${section_03_dir}/positive.control.transformed.file.txt
    ${R_directory}Rscript resources/genetics/plot_gwas.R \
        ${section_03_dir}/positive.control.transformed.file.txt \
        12 \
        1 \
        2 \
        3 \
        TRUE \
        ${positive_control_snp_chr} \
        ${positive_control_snp_pos} \
        ${positive_control_snp_window} \
        ${positive_control_threshold}

done

############################################################################################################
# negative control
############################################################################################################

echo "Running negative control"

seed=45516

tail -n +2 ./resource/genetics/mqtl_pos_ctr.tsv | while IFS=$'\t' read -r positive_control_cpg positive_control_snp_chr positive_control_snp_pos positive_control_snp_window positive_control_threshold
do
    negative_control_cpg="NEG_${positive_control_cpg}"

    echo "Processing negative control: $negative_control_cpg"

    # shuffle untransformed
    ${R_directory}Rscript resources/genetics/shuffle_control.R \
        ${untransformed_methylation_adjusted}.${positive_control_cpg}.positive_control \
        ${untransformed_methylation_adjusted}.${negative_control_cpg}.negative_control \
        $seed

    # shuffle transformed
    ${R_directory}Rscript resources/genetics/shuffle_control.R \
        ${transformed_methylation_adjusted}.${positive_control_cpg}.positive_control \
        ${transformed_methylation_adjusted}.${negative_control_cpg}.negative_control \
        $seed

    # make plink input
    ${R_directory}Rscript resources/genetics/make_control.R \
        ${untransformed_methylation_adjusted}.${negative_control_cpg}.negative_control \
        ${intersect_ids_plink} \
        ${untransformed_methylation_adjusted}.${negative_control_cpg}.negative_control.plink

    ${R_directory}Rscript resources/genetics/make_control.R \
        ${transformed_methylation_adjusted}.${negative_control_cpg}.negative_control \
        ${intersect_ids_plink} \
        ${transformed_methylation_adjusted}.${negative_control_cpg}.negative_control.plink

    # plink (untransformed)
    ${plink2} \
        --bfile ${bfile} \
        --pheno ${untransformed_methylation_adjusted}.${negative_control_cpg}.negative_control.plink \
        --glm allow-no-covars \
        --allow-extra-chr \
        --human \
        --output-chr 26 \
        --out ${section_03_dir}/negative_control_untransformed_${negative_control_cpg}

    tr -s " " < ${section_03_dir}/negative_control_untransformed_${negative_control_cpg}.PHENO1.glm.linear | gzip -c > ${section_03_dir}/negative_control_untransformed_${negative_control_cpg}.PHENO1.glm.linear.gz
    rm ${section_03_dir}/negative_control_untransformed_${negative_control_cpg}.PHENO1.glm.linear

    echo "make manhattan and qq plots (untransformed)"
    echo ${section_03_dir}/negative_control_untransformed_${negative_control_cpg}.PHENO1.glm.linear.gz > ${section_03_dir}/negative.control.untransformed.file.txt
    ${R_directory}Rscript resources/genetics/plot_gwas.R \
        ${section_03_dir}/negative.control.untransformed.file.txt \
        12 \
        1 \
        2 \
        3 \
        TRUE \
        ${positive_control_snp_chr} \
        ${positive_control_snp_pos} \
        ${positive_control_snp_window} \
        ${positive_control_threshold}

    # plink (transformed)
    ${plink2} \
        --bfile ${bfile} \
        --pheno ${transformed_methylation_adjusted}.${negative_control_cpg}.negative_control.plink \
        --glm allow-no-covars \
        --allow-extra-chr \
        --out ${section_03_dir}/negative_control_transformed_${negative_control_cpg}

    tr -s " " < ${section_03_dir}/negative_control_transformed_${negative_control_cpg}.PHENO1.glm.linear | gzip -c > ${section_03_dir}/negative_control_transformed_${negative_control_cpg}.PHENO1.glm.linear.gz
    rm ${section_03_dir}/negative_control_transformed_${negative_control_cpg}.PHENO1.glm.linear

    echo "make manhattan and qq plots (transformed)"
    echo ${section_03_dir}/negative_control_transformed_${negative_control_cpg}.PHENO1.glm.linear.gz > ${section_03_dir}/negative.control.transformed.file.txt
    ${R_directory}Rscript resources/genetics/plot_gwas.R \
        ${section_03_dir}/negative.control.transformed.file.txt \
        12 \
        1 \
        2 \
        3 \
        TRUE \
        ${positive_control_snp_chr} \
        ${positive_control_snp_pos} \
        ${positive_control_snp_window} \
        ${positive_control_threshold}

done

echo "Successfully completed script 1d"