#!/usr/bin/env bash

LC_NUMERIC="en_GB.UTF-8"

# logfiles
timetemp=$(date -u +%Y-%m-%d_%H-%M)

section_01_dir="${home_directory}/results/01"
section_02_dir="${home_directory}/results/02"
section_03_dir="${home_directory}/results/03"
section_04_dir="${home_directory}/results/04"
section_05_dir="${home_directory}/results/05"
section_06_dir="${home_directory}/results/06"
section_07_dir="${home_directory}/results/07"
section_08_dir="${home_directory}/results/08"
section_09_dir="${home_directory}/results/09"
section_10_dir="${home_directory}/results/10"
section_11_dir="${home_directory}/results/11"
section_12_dir="${home_directory}/results/12"
section_13_dir="${home_directory}/results/13"
section_14_dir="${home_directory}/results/14"
section_15_dir="${home_directory}/results/15"
section_16_dir="${home_directory}/results/16"
section_17_dir="${home_directory}/results/17"

section_01_logfiles="${section_01_dir}/logs/log${timetemp}.txt"
section_01a_logfile="${section_01_dir}/logs_a/log.txt"
section_01b_logfile="${section_01_dir}/logs_b/log.txt"
section_01c_logfile="${section_01_dir}/logs_c/log.txt"
section_01d_logfile="${section_01_dir}/logs_d/log.txt"
section_02a_logfile="${section_02_dir}/logs_a/log.txt"
section_02b_logfile="${section_02_dir}/logs_b/log.txt"
section_03a_logfile="${section_03_dir}/logs_a/log.txt"
section_03b_logfile="${section_03_dir}/logs_b/log.txt"
section_03c_logfile="${section_03_dir}/logs_c/log.txt"
section_03d_logfile="${section_03_dir}/logs_d/log.txt"
section_03e_logfile="${section_03_dir}/logs_e/log.txt"
section_03f_logfile="${section_03_dir}/logs_f/log.txt"
section_03g_logfile="${section_03_dir}/logs_g/log.txt"

section_04a_logfile="${section_04_dir}/logs_a/log.txt"
section_04b_logfile="${section_04_dir}/logs_b/log.txt"
section_04c_logfile="${section_04_dir}/logs_c/log.txt"
section_04d_logfile="${section_04_dir}/logs_d/log.txt"
section_04e_logfile="${section_04_dir}/logs_e/log.txt"
section_04f_logfile="${section_04_dir}/logs_f/log.txt"

section_05a_logfile="${section_05_dir}/logs_a/log.txt"
section_05b_logfile="${section_05_dir}/logs_b/log.txt"
section_05c_logfile="${section_05_dir}/logs_c/log.txt"
section_05d_logfile="${section_05_dir}/logs_d/log.txt"

section_06_logfile="${section_06_dir}/logs/log.txt"

section_07a_logfile="${section_07_dir}/logs_a/log.txt"
section_07b_logfile="${section_07_dir}/logs_b/log.txt"
section_07c_logfile="${section_07_dir}/logs_c/log.txt"
section_07d_logfile="${section_07_dir}/logs_d/log.txt"
section_08a_logfile="${section_08_dir}/logs_a/log.txt"
section_08b_logfile="${section_08_dir}/logs_b/log.txt"
section_08c_logfile="${section_08_dir}/logs_c/log.txt"

section_09_logfile="${section_09_dir}/logs/log.txt"
section_10a_logfile="${section_10_dir}/logs_a/log.txt" 
section_10b_logfile="${section_10_dir}/logs_b/log.txt"
section_11a_logfile="${section_11_dir}/logs_a/log.txt"
section_11b_logfile="${section_11_dir}/logs_b/log.txt"
section_11c_logfile="${section_11_dir}/logs_c/log.txt"
section_12_logfile="${section_12_dir}/logs/log.txt"
section_13a_logfile="${section_13_dir}/logs_a/log.txt"
section_13_logfile="${section_13_dir}/logs/log.txt"
section_14_logfile="${section_14_dir}/logs/log.txt"
section_15_logfile="${section_15_dir}/logs/log.txt"
section_16a_logfile="${section_16_dir}/logs_a/log.txt"
section_16b_logfile="${section_16_dir}/logs_b/log.txt"
section_16c_logfile="${section_16_dir}/logs_c/log.txt"
section_17a_logfile="${section_17_dir}/logs_a/log.txt"
section_17b_logfile="${section_17_dir}/logs_b/log.txt"

# ID lists
meth_ids="${home_directory}/processed_data/ids/meth_ids.txt"
intersect_ids_plink="${home_directory}/processed_data/ids/intersect_ids_plink.txt"
intersect_ids="${home_directory}/processed_data/ids/intersect_ids.txt"
covariates_intersect_gwas="${home_directory}/processed_data/covariate_data/covariates_gwas_intersectids.txt"
covariates_intersect_ewas="${home_directory}/processed_data/covariate_data/covariates_ewas_intersectids.txt"

# Sex prediction (methylation)
sex_discrepancies="${home_directory}/results/01/sex_discrepancies.RData"
sex_pred_plot="${home_directory}/results/01/XY_methylation_vs_sex.pdf"

# Check data
control_snps="${scripts_directory}/resources/genetics/snpsforbuildandposcheck"
miss_liftover="${section_01_dir}/miss_liftover.txt"
liftover_map="${home_directory}/processed_data/genetic_data/liftover_map.txt"
snpchrtxt="${section_01_dir}/no_snps_by_chr.txt"
snpchrplot="${section_01_dir}/no_snps_by_chr.pdf"
quality_scores_plot="${section_01_dir}/snp_quality.pdf"
ageplot="${section_01_dir}/age_distribution.pdf"
# positive_control_cpg="cg07959070" posive_control cpgs have been made into a list in resources/genetics/mqtl_pos_ctr.tsv
# positive_control_snp_chr="22"
# positive_control_snp_pos="50053871"
positive_control_file="${scripts_directory}/resources/genetics/mqtl_pos_ctr.tsv"
filt_positive_control_file="${scripts_directory}/resources/genetics/mqtl_pos_ctr_filt.tsv"
com_id="${scripts_directory}/resources/methylation/common_probe_ids.tsv"
positive_control_snp_window="100000"
positive_control_threshold="0.001"

# Descriptives
genetic_descriptives="${home_directory}/processed_data/ids/genetic_descriptives.RData"
methylation_descriptives="${home_directory}/processed_data/ids/methylation_descriptives.RData"
cnv_descriptives="${home_directory}/processed_data/ids/cnv_descriptives.RData"
covariate_descriptives="${home_directory}/processed_data/ids/covariate_descriptives.RData"
phenotype_descriptives="${home_directory}/processed_data/ids/phenotype_descriptives.RData"

cohort_descriptives="${section_01_dir}/cohort_descriptives.RData"
methylation_summary_gwas="${section_01_dir}/methylation_summary_gwas.RData"
methylation_summary_ewas="${section_01_dir}/methylation_summary_ewas.RData"
cohort_descriptives_was="${section_01_dir}/cohort_descriptives_was.RData"

# Clean genetic data
bfile="${home_directory}/processed_data/genetic_data/data"
#vcf_file="${home_directory}/processed_data/genetic_data/data.vcf"
tabfile="${home_directory}/processed_data/genetic_data/tabfile/data"
bfile_hm3="${home_directory}/processed_data/genetic_data/data_hm3"
tabfile_hm3="${home_directory}/processed_data/genetic_data/tabfile_hm3/data"
allele_ref_hm3="${home_directory}/processed_data/genetic_data/data_hm3.allele_codes"

pcaplot="${section_01_dir}/pcaplot.pdf"
allele_ref="${section_02_dir}/data.allele_codes.gz"
SNPfail1="${home_directory}/processed_data/genetic_data/SNPfail1.txt"
easyQC="${home_directory}/processed_data/genetic_data/data.easyqc"
easyQCfile="${home_directory}/processed_data/genetic_data/CLEANED.data.easyqc.gz"
easyQCscript="${scripts_directory}/resources/genetics/easyQC_topmed.ecf"
genetic_processed_dir="${home_directory}/processed_data/genetic_data"

# CNV file
#tabcnv="${home_directory}/processed_data/cnv_data/tabfile/data"

# Inversions files
inv_processed_dir="${home_directory}/processed_data/inversions"
tabinv="${home_directory}/processed_data/inversions/data"
inv_snps="${scripts_directory}/resources/inversions/mapSNPs.tab"
bfile_inv="${home_directory}/processed_data/inversions/inversions"

# Kinship files
grmfile_all="${home_directory}/processed_data/genetic_data/data"
grmfile_fast="${home_directory}/processed_data/genetic_data/data_fast"
grmfile_relateds="${home_directory}/processed_data/genetic_data/data_relateds"
grmfile_unrelateds="${home_directory}/processed_data/genetic_data/data_unrelateds"

# PCA files
pca="${home_directory}/processed_data/genetic_data/pca"
pcs_all="${pca}.eigenvec"

# Cell count
format_measured_cellcounts="${home_directory}/processed_data/cellcounts/measured_cellcounts.format.txt"
cellcounts="${home_directory}/processed_data/methylation_data/cellcounts.txt"
cellcounts_tf="${home_directory}/processed_data/cellcounts/cellcounts.transformed.txt"
cellcounts_tf_smok="${home_directory}/processed_data/cellcounts/cellcounts.transformed.smokingadj.txt"
cellcounts_entropy="${home_directory}/processed_data/cellcounts/cellcounts_entropy.txt"
cellcounts_plink="${home_directory}/processed_data/cellcounts/cellcounts.transformed.plink"
cellcounts_plink_raw="${home_directory}/processed_data/cellcounts/cellcounts.raw.plink"
cellcounts_plink_smokadj="${home_directory}/processed_data/cellcounts/cellcounts.transformed.smokadj.plink"
cellcounts_SD="5"
cellcounts_plot="${section_01_dir}/cellcounts_plot.pdf"
cellcounts_summary="${section_01_dir}/cellcounts_summary.txt"
cellcounts_gwa="${home_directory}/processed_data/cellcounts/cellcounts.houseman.txt"
cellcounts_cov="${home_directory}/processed_data/cellcounts/cellcounts.covariates.txt"
cor_matrix="${section_01_dir}/cor_matrix.txt"
cor_plot="${section_01_dir}/cor_plot.pdf"

# Covariates
covariates_combined="${home_directory}/processed_data/methylation_data/all_covariates"
ccovar_file="${home_directory}/processed_data/methylation_data/ccovar_file.txt"
qcovar_file="${home_directory}/processed_data/methylation_data/qcovar_file.txt"
genetic_pc_gwas="${home_directory}/processed_data/genetic_data/genetic_pc_gwas.txt"
qcovar_noPC_file="${home_directory}/processed_data/methylation_data/qcovar_noPC_file.txt"

# phenotype files
winsorized_pheno="${home_directory}/processed_data/phenotype_data/winsorized_pheno.Robj"
raw_phenotype_distribution_plot="${home_directory}/results/01/raw_phenotype_distribution_plot"
raw_phenotype_summary_file="${home_directory}/results/01/raw_phenotypes_summary"
edited_phenotype_distribution_plot="${home_directory}/results/01/edited_phenotype_distribution_plot"
edited_phenotype_summary_file="${home_directory}/results/01/edited_phenotypes_summary"
winsorized_phenotype_file="${home_directory}/processed_data/phenotype_data/winsorized_phenotypes.RData"

meth_pcs_transformed="${home_directory}/processed_data/methylation_data/meth_pcs_transformed"
meth_pcs_untransformed="${home_directory}/processed_data/methylation_data/meth_pcs_untransformed"
nongenetic_meth_pcs_transformed="${home_directory}/processed_data/methylation_data/meth_pcs_nongenetic_transformed"
nongenetic_meth_pcs_untransformed="${home_directory}/processed_data/methylation_data/meth_pcs_nongenetic_untransformed"
gwas_covariates="${home_directory}/processed_data/genetic_data/gwas_covariates"

# SNP list files
#hm3_snps="${scripts_directory}/resources/genetics/hapmap3_autosome.snplist.gz"
ilmn_probesnps="${scripts_directory}/resources/qc/probesnps.txt"
#hm3_snps_no_ld="${scripts_directory}/resources/genetics/hapmap3_autosome.snplist_withoutlong-range.LDSNPs.txt.gz"
#hm3_snps_no_ld2="${scripts_directory}/resources/genetics/hapmap3_autosome.snplist_withoutlong-range.LDSNPs.txt"
hm3_snps="${scripts_directory}/resources/genetics/hapmap3_autosome_withoutlong-range.LDSNPs.recode.snplist.gz"


# Sample mixup checks
bfile_probesnps="${bfile}_probesnps"

# ID lists
genetic_outlier_ids="${home_directory}/processed_data/genetic_data/genetic_outliers.txt"
methylation_ids="${home_directory}/processed_data/genetic_data/methylation_ids.txt"

# Methylation files
methylation_no_outliers_gwas="${home_directory}/processed_data/methylation_data/methylation_no_outliers_gwas.Robj"
methylation_no_outliers_ewas="${home_directory}/processed_data/methylation_data/methylation_no_outliers_ewas.Robj"
normalized_between_datasets="${home_directory}/processed_data/methylation_data/normalized_between_datasets.Robj"

transformed_methylation_adjusted="${home_directory}/processed_data/methylation_data/transformed_methylation_adjusted"
untransformed_methylation_adjusted="${home_directory}/processed_data/methylation_data/untransformed_methylation_adjusted"
transformed_methylation_adjusted_pcs="${home_directory}/processed_data/methylation_data/transformed_methylation_adjusted_pcs"
untransformed_methylation_adjusted_pcs="${home_directory}/processed_data/methylation_data/untransformed_methylation_adjusted_pcs"
methylation_subset="${home_directory}/processed_data/methylation_data/methylation_subset"
outlier_count="${home_directory}/processed_data/methylation_data/outlier_count.txt"

# Smoking prediction
methylation_processed_dir="${home_directory}/processed_data/methylation_data"
smoking_pred="${methylation_processed_dir}/smoking_prediction"
smoking_age_pred_plot="${section_01_dir}/smoking_age_prediction.pdf"
smoking_pred_SD="5"

age_smoking_prediction_plot="${home_directory}/results/01/age_smoking_prediction_plot"
updated_phenotype_file="${home_directory}/processed_data/phenotype_data/updated_winsorized_phenotypes.RData"
predicted_smoking="${home_directory}/results/01/predicted_smoking.txt"

# Age prediction
age_pred="${home_directory}/processed_data/methylation_data/age_prediction"
age_pred_sumstats="${section_01_dir}/age_prediction_stats"
age_pred_plot="${section_01_dir}/age_prediction"
age_pred_clock="${section_01_dir}/age_clock.txt"
age_pred_SD="5"


# Results locations
matrixeqtl_mqtl_dir="${home_directory}/results/05"
matrixeqtl_vmqtl_dir="${home_directory}/results/06"
matrixeqtl_mcnv_dir="${home_directory}/results/07"
ewas_results_dir="${home_directory}/results/08"
gwas_aar_dir="${home_directory}/results/10"
gwas_smoking_dir="${home_directory}/results/11"
gwas_cellcount_entropy_dir="${home_directory}/results/11"
gwas_cellcounts_dir="${home_directory}/results/12"
gwas_cellcounts_mvlmm_dir="${home_directory}/results/13"

resname="res"

#HASE
hase_dir_plink="${home_directory}/processed_data/hase/hase_plink"
hase_dir_in="${home_directory}/processed_data/hase/hase_in"
hase_converting="${home_directory}/processed_data/hase/hase_converting"
hase_pheno="${home_directory}/processed_data/hase/hase_pheno"
hase_cov="${home_directory}/processed_data/hase/hase_cov"
hase_cov_females="${home_directory}/processed_data/hase/hase_cov_females"
hase_cov_males="${home_directory}/processed_data/hase/hase_cov_males"
hase_encoding="${home_directory}/processed_data/hase/encoding"
hase_mapping="${home_directory}/processed_data/hase/mapped"
hase_single_site="${home_directory}/processed_data/hase/single_site"

#vmeQTL
meth_vmeQTL_directory="${home_directory}/processed_data/methylation_data/vmeQTL"
meth_vmeQTL_input_chr="${meth_vmeQTL_directory}/meth_vmeQTL_input.chr"
meth_vmeQTL_annotation="${scripts_directory}/resources/methylation/vmeQTL/EPIC_annotation_autochr"
vmeQTL_thread="10"


# SFTP details
# This is the location your results will be uploaded
# Note: No individual data will be uploaded to this location during the course of the pipeline
sftp_address="sftp.acrc.bris.ac.uk"

if [ "$sftp_username" = "gh13047" ] || [ "$sftp_username" = "epzjlm" ] || [ "$sftp_username" = "godmc" ] || [ "$sftp_username" = "epwkb" ]
then
	sftp_path="/sftp/resources"
        
else
	sftp_path="/sftp/resources"

fi

# scripts and binaries
plink="${scripts_directory}/resources/bin/plink1.90"
plink2="${scripts_directory}/resources/bin/plink2"
gcta="${scripts_directory}/resources/bin/gcta-1.94.1"
gemma="${scripts_directory}/resources/bin/gemma"
hase="${scripts_directory}/resources/bin/hase"
osca="${scripts_directory}/resources/bin/osca"
smr="${scripts_directory}/resources/bin/smr-1.3.1"

# Functions

vercomp () {
        if [[ $1 == $2 ]]
        then
                echo "0"
                return 0
        fi
        local IFS=.
        local i ver1=($1) ver2=($2)
        # fill empty fields in ver1 with zeros
        for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
        do
                ver1[i]=0
        done
        for ((i=0; i<${#ver1[@]}; i++))
        do
                if [[ -z ${ver2[i]} ]]
                then
                        # fill empty fields in ver2 with zeros
                        ver2[i]=0
                fi
                if ((10#${ver1[i]} > 10#${ver2[i]}))
                then
                        echo "0"
                        return 0
                fi
                if ((10#${ver1[i]} < 10#${ver2[i]}))
                then
                        echo "1"
                        return 0
                fi
        done
        echo "Correct script version"
        echo "0"
        return 0
}


print_version () {

	current_time=`date`
	version=`git tag | tail -n 1`
	a=`git --version | cut -d " " -f 3`
	b=`vercomp $a 1.8.4.2`
	if [ "$b" -eq "1" ]
	then
		echo "git version:"
		echo "$a"

		echo "DEEP version ${version}"
		echo "Current time: ${current_time}"

		echo "This git version is too early to handle proper version checking."
		echo "Please ensure that your scripts are up to date."
		echo "If in doubt, run 'git pull'"
		return 0
	fi

	commit=`git rev-parse HEAD`
	commit_date=`git show -s --format=%ci`
	echo ""
	echo ""
	echo "DEEP version ${version}"
	echo "Commit: ${commit}"	
	echo "Commit date: ${commit_date}"
	echo "Current time: ${current_time}"
	echo ""
	echo "Please ensure your scripts are up to date."
	echo "If in doubt, run 'git pull'"
	echo ""
	echo ""

}

